// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: backend/proto/analytics/analytics.proto

package analytics

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LogEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	EventType     string                 `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	EventDataJson string                 `protobuf:"bytes,3,opt,name=event_data_json,json=eventDataJson,proto3" json:"event_data_json,omitempty"`
	Timestamp     string                 `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEventRequest) Reset() {
	*x = LogEventRequest{}
	mi := &file_backend_proto_analytics_analytics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEventRequest) ProtoMessage() {}

func (x *LogEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_proto_analytics_analytics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEventRequest.ProtoReflect.Descriptor instead.
func (*LogEventRequest) Descriptor() ([]byte, []int) {
	return file_backend_proto_analytics_analytics_proto_rawDescGZIP(), []int{0}
}

func (x *LogEventRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *LogEventRequest) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *LogEventRequest) GetEventDataJson() string {
	if x != nil {
		return x.EventDataJson
	}
	return ""
}

func (x *LogEventRequest) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

type LogEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEventResponse) Reset() {
	*x = LogEventResponse{}
	mi := &file_backend_proto_analytics_analytics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEventResponse) ProtoMessage() {}

func (x *LogEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backend_proto_analytics_analytics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEventResponse.ProtoReflect.Descriptor instead.
func (*LogEventResponse) Descriptor() ([]byte, []int) {
	return file_backend_proto_analytics_analytics_proto_rawDescGZIP(), []int{1}
}

func (x *LogEventResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *LogEventResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_backend_proto_analytics_analytics_proto protoreflect.FileDescriptor

const file_backend_proto_analytics_analytics_proto_rawDesc = "" +
	"\n" +
	"'backend/proto/analytics/analytics.proto\x12\tanalytics\"\x8f\x01\n" +
	"\x0fLogEventRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\x12&\n" +
	"\x0fevent_data_json\x18\x03 \x01(\tR\reventDataJson\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\tR\ttimestamp\"F\n" +
	"\x10LogEventResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2W\n" +
	"\x10AnalyticsService\x12C\n" +
	"\bLogEvent\x12\x1a.analytics.LogEventRequest\x1a\x1b.analytics.LogEventResponseB-Z+github.com/playkaro/backend/proto/analyticsb\x06proto3"

var (
	file_backend_proto_analytics_analytics_proto_rawDescOnce sync.Once
	file_backend_proto_analytics_analytics_proto_rawDescData []byte
)

func file_backend_proto_analytics_analytics_proto_rawDescGZIP() []byte {
	file_backend_proto_analytics_analytics_proto_rawDescOnce.Do(func() {
		file_backend_proto_analytics_analytics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_backend_proto_analytics_analytics_proto_rawDesc), len(file_backend_proto_analytics_analytics_proto_rawDesc)))
	})
	return file_backend_proto_analytics_analytics_proto_rawDescData
}

var file_backend_proto_analytics_analytics_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_backend_proto_analytics_analytics_proto_goTypes = []any{
	(*LogEventRequest)(nil),  // 0: analytics.LogEventRequest
	(*LogEventResponse)(nil), // 1: analytics.LogEventResponse
}
var file_backend_proto_analytics_analytics_proto_depIdxs = []int32{
	0, // 0: analytics.AnalyticsService.LogEvent:input_type -> analytics.LogEventRequest
	1, // 1: analytics.AnalyticsService.LogEvent:output_type -> analytics.LogEventResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_backend_proto_analytics_analytics_proto_init() }
func file_backend_proto_analytics_analytics_proto_init() {
	if File_backend_proto_analytics_analytics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_backend_proto_analytics_analytics_proto_rawDesc), len(file_backend_proto_analytics_analytics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_backend_proto_analytics_analytics_proto_goTypes,
		DependencyIndexes: file_backend_proto_analytics_analytics_proto_depIdxs,
		MessageInfos:      file_backend_proto_analytics_analytics_proto_msgTypes,
	}.Build()
	File_backend_proto_analytics_analytics_proto = out.File
	file_backend_proto_analytics_analytics_proto_goTypes = nil
	file_backend_proto_analytics_analytics_proto_depIdxs = nil
}
