// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AuthPayload struct {
	Token string `json:"token"`
	User  *User  `json:"user"`
}

type Match struct {
	ID        string  `json:"id"`
	TeamA     string  `json:"teamA"`
	TeamB     string  `json:"teamB"`
	StartTime string  `json:"startTime"`
	Status    string  `json:"status"`
	OddsTeamA float64 `json:"oddsTeamA"`
	OddsTeamB float64 `json:"oddsTeamB"`
	OddsDraw  float64 `json:"oddsDraw"`
}

type Mutation struct {
}

type Query struct {
}

type User struct {
	ID       string  `json:"id"`
	Username string  `json:"username"`
	Email    string  `json:"email"`
	Mobile   *string `json:"mobile,omitempty"`
	KycLevel int     `json:"kycLevel"`
	Wallet   *Wallet `json:"wallet,omitempty"`
}

type Wallet struct {
	ID       string  `json:"id"`
	Balance  float64 `json:"balance"`
	Currency string  `json:"currency"`
	Bonus    float64 `json:"bonus"`
}
